=pod

=head1 Eureca Idea Web Portal

L<Eureca> is a software that provide an c<simple> and c<effective> interface to 
employees can post ideas for company or business improvement.

Think about it...

You have a company with many and many employees and you like to listen all of your 
employees ideas that can be positives to make improvements on your company but you 
dont have many time to listen one per time.

Installing L<Eureca> you can provide a channel to your employee start to contribute 
posting some ideas (based on criteria, obviously) and you can check on your free 
time.


=head3 Who can use it?

Anyone can download a copy of this software, install on server and use!


=head3 What do I need to take to install then?

=over

=item Perl 5.10+

=item Mojolicious 4+ (and some plugins)

=item ObjectDB ORM

=item SQLite driver for DBI

(or your favorite database ;] ) 

=back


=head3 How can I test/run?

You can use L<morbo> that is an development perl server for mojolicious to run
L<Eureca> on your machine:

    $ morbo eureca/index.pl

or you can use L<hipnotoad> for production deployment.


=head3 Author

2013 (c) Bivee

L<http://bivee.com.br>


=head3 Copyright and License

This software is copyright (c) 2013 by Bivee.

This is a free software; you can redistribute it and/or modify it under the same terms of Perl 5 programming 
languagem system itself.

=cut
